environment: team10
management:
  endpoints:
    web:
      exposure:
        include: '*'
yolt:
  vault:
    auth:
      max-refresh-before-token-expiry-hours: 3
spring:
  # We want to be able to override config server during development with env vars
  cloud:
    config:
      overrideSystemProperties: false