apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-gateway
spec:
  template:
    spec:
      containers:
        - name: client-proxy
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: team,$(ENVIRONMENT),$(NAMESPACE),$(ENVIRONMENT)-$(NAMESPACE)
