apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-gateway
  labels:
    team: yts-clients
    git.yolt.io/group: backend
    git.yolt.io/project: client-gateway
    git.yolt.io/tag: $(TAG)
    yolt.io/config-server-tag: $(CONFIG_SERVER_TAG)
spec:
  replicas: 1
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      name: client-gateway
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/agent-revoke-grace: "60"
        vault.hashicorp.com/agent-revoke-on-shutdown: "true"
        vault.hashicorp.com/agent-cache-enable: "false"
        vault.hashicorp.com/agent-pre-populate: "false"
        vault.hashicorp.com/agent-limits-cpu: 500m
        vault.hashicorp.com/agent-limits-mem: 128Mi
        vault.hashicorp.com/agent-requests-cpu: 10m
        vault.hashicorp.com/agent-requests-mem: 64Mi
        vault.hashicorp.com/auth-path: "auth/$(ENVIRONMENT)/k8s/eks/pods/$(NAMESPACE)"
        vault.hashicorp.com/role: client-gateway
        vault.hashicorp.com/agent-inject-secret-client_proxy_cert: ""
        vault.hashicorp.com/agent-inject-template-client_proxy_cert: |
          {{ with secret "$(ENVIRONMENT)/k8s/pods/$(NAMESPACE)/pki/issue/client-gateway" "common_name=client-proxy" }}
          {{- .Data.certificate -}}
          {{ end }}
        vault.hashicorp.com/agent-inject-secret-client_proxy_private_key: ""
        vault.hashicorp.com/agent-inject-template-client_proxy_private_key: |
          {{ with secret "$(ENVIRONMENT)/k8s/pods/$(NAMESPACE)/pki/issue/client-gateway" "common_name=client-proxy" }}
          {{- .Data.private_key -}}
          {{ end }}
        vault.hashicorp.com/agent-inject-secret-client_proxy_issuing_ca: ""
        vault.hashicorp.com/agent-inject-template-client_proxy_issuing_ca: |
          {{ with secret "$(ENVIRONMENT)/k8s/pods/$(NAMESPACE)/pki/issue/client-gateway" "common_name=client-proxy" }}
          {{- .Data.issuing_ca -}}
          {{ end }}
        vault.hashicorp.com/agent-inject-secret-kafka_private_key: ""
        vault.hashicorp.com/agent-inject-template-kafka_private_key: |
          {{ with secret "$(ENVIRONMENT)/kafka/issue/client-users" "common_name=client-users" }}
          {{- .Data.private_key -}}
          {{ end }}
        vault.hashicorp.com/agent-inject-secret-kafka_issuing_ca: ""
        vault.hashicorp.com/agent-inject-template-kafka_issuing_ca: |
          {{ with secret "$(ENVIRONMENT)/kafka/issue/client-users" "common_name=client-users" }}
          {{- .Data.issuing_ca -}}
          {{ end }}
        vault.hashicorp.com/agent-inject-secret-kafka_cert: ""
        vault.hashicorp.com/agent-inject-template-kafka_cert: |
          {{ with secret "$(ENVIRONMENT)/kafka/issue/client-users" "common_name=client-users" }}
          {{- .Data.certificate -}}
          {{ end }}
        vault.hashicorp.com/agent-inject-command-client_proxy_cert: openssl pkcs12 -export -in /vault/secrets/client_proxy_cert -inkey /vault/secrets/client_proxy_private_key -out /vault/secrets/client_proxy-keystore.p12 -name keystore -passout pass:dontchangeit
        vault.hashicorp.com/client-max-retries: "4"
        prometheus.io/scrape: "true"
        prometheus.io/path: /actuator/prometheus
        prometheus.io/port: "8444"
        prometheus.io/scheme: https
        ca-certificates.yolt.io/inject: "true"
      labels:
        team: yts-clients
        serving: "true"
    spec:
      containers:
        - env:
            - name: SPRING_PROFILES_ACTIVE
              value: $(ENVIRONMENT),$(NAMESPACE),$(ENVIRONMENT)-$(NAMESPACE)
            - name: SPRING_CLOUD_CONFIG_LABEL
              value: $(CONFIG_SERVER_TAG)
          envFrom:
            - configMapRef:
                name: kafka
          image: $(DOCKER_REGISTRY)/client-proxy:$(DOCKER_TAG)
          lifecycle:
            preStop:
              exec:
                command:
                  - sh
                  - -c
                  - sleep 10
          livenessProbe:
            httpGet:
              path: actuator/health/liveness
              port: 8444
              scheme: HTTPS
            initialDelaySeconds: 180
            timeoutSeconds: 6
          name: client-proxy
          ports:
            - containerPort: 8443
          readinessProbe:
            httpGet:
              path: actuator/health/readiness
              port: 8444
              scheme: HTTPS
          securityContext:
            readOnlyRootFilesystem: true
            runAsGroup: 1000
            runAsNonRoot: true
            runAsUser: 100
          volumeMounts:
            - mountPath: /tmp
              name: tmp-volume
          resources:
            requests:
              cpu: 25m # peak in yfb-acc performance test
              memory: 300Mi
      initContainers:
        - command:
            - sh
            - -c
            - until $(curl --connect-timeout 2 --output /dev/null --silent --head --fail https://config-server/config-server/actuator/health); do echo waiting for config-server; sleep 2; done;
          image: $(DOCKER_REGISTRY)/client-proxy:$(DOCKER_TAG)
          name: wait-for-config-server
          resources:
            limits:
              memory: 150Mi
            requests:
              memory: 25Mi
              cpu: 10m
      securityContext:
        fsGroup: 1000
        runAsGroup: 1000
        runAsUser: 100
      serviceAccountName: client-gateway
      terminationGracePeriodSeconds: 180
      volumes:
        - emptyDir: {}
          name: tmp-volume
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: name
                      operator: In
                      values:
                        - client-gateway
                topologyKey: topology.kubernetes.io/zone
