apiVersion: v1
kind: Service
metadata:
  # Intentionally not 'client-gateway'.
  # The ingress configuration expects the old name.
  name: client-proxy
  labels:
    team: yts-clients
spec:
  selector:
    name: client-gateway
    serving: "true"
  ports:
    - port: 443
      name: https
      targetPort: 8443
